### ISSUE TITLE
Not all words are matched

### ISSUE THREAD

**Issue by maxtepkeev** [abusix/ahocorapy#1]
Hi,

Thanks for this pure python implementation which performs really awesome under pypy.

However we found out that under some circumstances not all words are matched, consider the following example:

```python
text = '/foo/bar'
words = ['/bar', '/foo/bar', 'bar']
tree = KeywordTree(case_insensitive=True)
for word in words:
    tree.add(word)
tree.finalize()
print set([word for word, position in tree.search_all(text)])  # set(['/foo/bar', '/bar'])
```

The expected result would be ``set(['/foo/bar', '/bar', 'bar'])`` but we got only ``set(['/foo/bar', '/bar'])``

**Comment by FrederikP** [comment]
Hi,

thanks for the report. I'll have a look.
The search_all process is kind of tricky due to the shortcutting approach taken in addition to the usual aho-corasick algorithm.
I guess I missed a scenario there. Thanks for providing an example, this is ideal for reproducing.

**Comment by maxtepkeev** [comment]
Hi @FrederikP 

Thanks! This issue is the only thing that stops us from using this wonderful aho-corasick implementation in production, so we're really waiting for the fix.

Thanks again.

**Comment by FrederikP** [comment]
That's great to hear.
We are using the library in production, but we are currently only interested that at least one keyword is contained and not in all results. I added the search_all method when we open sourced it hoping someone else might find it useful. It's great that you found this bug.

I can reproduce the bug. Using the visualization I can see what's missing:

![example](https://user-images.githubusercontent.com/483596/37828329-1ad14ba6-2e9b-11e8-9c66-224c97cd38d5.png)

As you can see 'bar' is in the list of results in node 4 (and 14 of course) but not in node 11. It also needs to be in 11. I'll work on a fix.

**Comment by maxtepkeev** [comment]
That's awesome. Thanks. As soon as the fix is available I can test it on the real world data to be sure that it works fine. At the moment we're using the ``esmre``, so we can easily compare the results to be sure that they're the same with ``ahocorapy``.

**Comment by FrederikP** [comment]
The tests are green, so I'll release a new version.
If you find any other problems with the new version please don't hesitate to open up a new issue! It's a great help.

The fix might change performance characteristics slightly, but see for yourself.
Version 1.4.1 should be available in a few minutes.

**Comment by FrederikP** [comment]
It's up @ https://pypi.python.org/pypi/ahocorapy
