### ISSUE TITLE
pickle issue

### ISSUE THREAD

**Issue by yoch** [abusix/ahocorapy#5]
Seems that the keyword tree isn't picklable, I got maximum recursion error when I try.

**Comment by FrederikP** [comment]
Hi, thanks for the report. 
Without testing I'm pretty sure what you say is correct. I haven't really focused on making it pickable yet, after introducing some major changes in the beginning of this year.
I will have a look and see how difficult it is.

**Comment by FrederikP** [comment]
I added a (simple) pickling test in https://github.com/abusix/ahocorapy/commit/7ad85b2a391f6194eef00ec605f3c06e228f470f . 
It's green. Maybe it's because the example is quite small and simple. Maybe it has to do with python version. Can you give me some more detail on your failing example?

**Comment by FrederikP** [comment]
Also. If you have a really big set of keywords, the resulting tree will be very recursive:

From the python [docs:](https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled)

> Trying to pickle a highly recursive data structure may exceed the maximum recursion depth, a RecursionError will be raised in this case. You can carefully raise this limit with sys.setrecursionlimit().

So you can raise the recursion limit for now. But if you provide me an example I will have a look into improving the pickling by replacing reference recursion with indices or something like that.

**Comment by FrederikP** [comment]
To fix the python27 problems with pickling, I went ahead and implemented non-recursive pickling.
Can you try if version 1.5.0 fixes your issues? (I haven't done any performance testing on this yet, so pickling and unpickling huge trees might still be quite a resource hungry and time intensive operation)

**Comment by yoch** [comment]
Hello,

I use python 3.5, and simply tested by pickling the benchmark's keyword tree.

Now after your fix, it doesn't finish (at this time, after some minutes running).

**Comment by FrederikP** [comment]
Ah okay. That helps. That's a pretty big tree. Let me check if I can see why it takes forever and optimize.

That said it looks like it's working fine for smaller trees.

**Comment by FrederikP** [comment]
Okay I figured out why (some naive array resizing in custom pickling).

Can you try version 1.5.1 when you have a chance?

For me running https://github.com/abusix/ahocorapy/blob/master/tests/ahocorapy_pickle_performance_test.py works and outputs:

```
Serialization took: 0.92s
Deserialization took: 0.94s
```

**Comment by yoch** [comment]
Okay, it works for me as well. Thank you !

**Comment by FrederikP** [comment]
Great to hear. Thanks for letting me know.
If you have any problems going forward, just open another issue.
