### ISSUE TITLE
kwtree.finalize() cost too long,is there any way to speed up the stage?

### ISSUE THREAD

**Issue by delltower** [abusix/ahocorapy#6]

**Comment by FrederikP** [comment]
Hi,
I'll need some more info to do anything with this issue.
What does your data look like?
How are you using the library?
Have you considered an alternative with C extension? (e.g. https://pypi.org/project/pyahocorasick/) It will be faster, as can be seen in the benchmark provided. 

I have done several optimization iterations with this library, if you or anyone else finds a way to speed it up, I'm happy about PRs.

I'll close this for now, as it's not really an issue. I implemented the Aho Corasick algorithm with some adjustments and the rest is just how fast/slow the python interpreter is. You can see in the benchmark that the library performs much faster when used with pypy for example.
